<?php
declare(strict_types=1);

// NekosiaNeko SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

NekosiaNekoUtility::setRegistrar(function (NekosiaNekoUtility $u): void {
    $u->clean = [NekosiaNekoClean::class, 'call'];
    $u->done = [NekosiaNekoDone::class, 'call'];
    $u->make_error = [NekosiaNekoMakeError::class, 'call'];
    $u->feature_add = [NekosiaNekoFeatureAdd::class, 'call'];
    $u->feature_hook = [NekosiaNekoFeatureHook::class, 'call'];
    $u->feature_init = [NekosiaNekoFeatureInit::class, 'call'];
    $u->fetcher = [NekosiaNekoFetcher::class, 'call'];
    $u->make_fetch_def = [NekosiaNekoMakeFetchDef::class, 'call'];
    $u->make_context = [NekosiaNekoMakeContext::class, 'call'];
    $u->make_options = [NekosiaNekoMakeOptions::class, 'call'];
    $u->make_request = [NekosiaNekoMakeRequest::class, 'call'];
    $u->make_response = [NekosiaNekoMakeResponse::class, 'call'];
    $u->make_result = [NekosiaNekoMakeResult::class, 'call'];
    $u->make_point = [NekosiaNekoMakePoint::class, 'call'];
    $u->make_spec = [NekosiaNekoMakeSpec::class, 'call'];
    $u->make_url = [NekosiaNekoMakeUrl::class, 'call'];
    $u->param = [NekosiaNekoParam::class, 'call'];
    $u->prepare_auth = [NekosiaNekoPrepareAuth::class, 'call'];
    $u->prepare_body = [NekosiaNekoPrepareBody::class, 'call'];
    $u->prepare_headers = [NekosiaNekoPrepareHeaders::class, 'call'];
    $u->prepare_method = [NekosiaNekoPrepareMethod::class, 'call'];
    $u->prepare_params = [NekosiaNekoPrepareParams::class, 'call'];
    $u->prepare_path = [NekosiaNekoPreparePath::class, 'call'];
    $u->prepare_query = [NekosiaNekoPrepareQuery::class, 'call'];
    $u->graphql_body = [NekosiaNekoGraphql::class, 'body'];
    $u->graphql_errors = [NekosiaNekoGraphql::class, 'errors'];
    $u->result_basic = [NekosiaNekoResultBasic::class, 'call'];
    $u->result_body = [NekosiaNekoResultBody::class, 'call'];
    $u->result_headers = [NekosiaNekoResultHeaders::class, 'call'];
    $u->transform_request = [NekosiaNekoTransformRequest::class, 'call'];
    $u->transform_response = [NekosiaNekoTransformResponse::class, 'call'];
});
